# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Automated deployments by Keel
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keel.sh" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
# comment line above and uncomment this for local development

markdown: kramdown
permalink: pretty
# Markdown settings
# markdown: kramdown
# kramdown:
#   input: GFM
#   # hard_wrap: false
#   syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# this goes inside _config.yml. Change as required
navigation:
- text: About
  url: /
- text: Install
  url: /install/
- text: User Guide
  url: /user-guide/

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-seo-tag

# social networks
social:
  twitter: https://twitter.com/KRusenas
  github: https://github.com/rusenask/keel
